name = "test-ws"
main = "src/worker.js"
compatibility_date = "2023-06-22"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "Room" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room"]